### ISSUE TITLE
bad argument #1 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by SonaliBendre** [Tatsh/mpv-netrc#2]

**Comment by Tatsh** [comment]
I need more info. My code never calls `ipairs`.

**Comment by SonaliBendre** [comment]
[netrc]
[netrc] stack traceback:
[netrc]         mp.defaults:597: in function 'handler'
[netrc]         mp.defaults:510: in function 'call_event_handlers'
[netrc]         mp.defaults:552: in function 'dispatch_events'
[netrc]         mp.defaults:503: in function <mp.defaults:502>
[netrc]         [C]: at 0x7ff655bade20
[netrc]         [C]: at 0x7ff655bae310

**Comment by SonaliBendre** [comment]
maybe that was other script error

**Comment by Tatsh** [comment]
What other plugins do you have?

**Comment by aicynide** [comment]
> What other plugins do you have?

I mean `bad argument #1 'ipairs' (table expected, got nil)` was due to recentmenu.lua script

**Comment by aicynide** [comment]
> [netrc] [netrc] stack traceback: [netrc] mp.defaults:597: in function 'handler' [netrc] mp.defaults:510: in function 'call_event_handlers' [netrc] mp.defaults:552: in function 'dispatch_events' [netrc] mp.defaults:503: in function mp.defaults:502 [netrc] [C]: at 0x7ff655bade20 [netrc] [C]: at 0x7ff655bae310

Please fix this error

**Comment by Tatsh** [comment]
I am not getting this error (and I do have more plugins than just mpv-netrc). I cannot tell from the backtrace you have where netrc is causing the issue.

What are the steps to reproduce this? What plugins do you have installed?
